# Build Android
name: Android Build
# Define on which Github event, workflow will trigger
on:
  pull_request:
    branches: 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build with Gradle
        run: ./gradlew assemble
